### ISSUE TITLE
NFT collection smart contract

### ISSUE THREAD

**Issue by SHEDEVERstudio** [SHEDEVERstudio/SHEDGEMS#7]
Write a smart contract for mint NFT collection (ERC-721) in Tact.
The smart contract should allow the owner to change the metadata of the collection and individual NFTs

Also, see how similar was implemented on func contracts:

nft-collection - [contractV1](https://github.com/getgems-io/nft-contracts/blob/main/packages/contracts/sources/nft-collection-editable.fc), [contractV2](https://github.com/getgems-io/nft-contracts/blob/main/packages/contracts/sources/nft-collection-editable-v2.fc)
nft-item - [contractV1](https://github.com/getgems-io/nft-contracts/blob/main/packages/contracts/sources/nft-item-editable-DRAFT.fc), [contractV2](https://github.com/getgems-io/nft-contracts/blob/main/packages/contracts/sources/nft-item-editable-v2.fc)

**Comment by hitaspdotnet** [comment]
I like to implement this. I have [already coded](https://github.com/hitaspdotnet/nft-enforced-royalty) NFT with enforced royalties, I can implement that or same as current standard.
https://hitasp.t.me
